name: Build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 17
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Patch
        run: ./gradlew applyPatches --stacktrace
      - name: Get MC Version
        run: echo "::set-output name=mcver::$(grep mcVersion gradle.properties | awk '{print $3;}')"
        id: mcver
      - name: Build
        run: |
          ./gradlew build -x test --stacktrace --no-daemon
          ./gradlew createReobfPaperclipJar --stacktrace --no-daemon
      - name: Archive Paperclip
        uses: actions/upload-artifact@v2
        with:
          name: Hurricane
          path: build/libs/hurricane-paperclip-${{ steps.mcver.outputs.mcver }}-R0.1-SNAPSHOT-reobf.jar
